name: Build with Nikola

on:
  workflow_call:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Build the Ansible community website'
    steps:
    - name: Check out the website repository
      uses: actions/checkout@v3
    - name: Build the site with Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: true
